### ISSUE TITLE
Won't Randomize

### ISSUE THREAD

**Issue by princessGasmask** [Herringway/disgaea-fiesta#1]
Hey, sorry to necro-bump but I've been interested in a unit randomizer for these games for a long time and this one's the only one I could find. I got the script up and running, but my issue is that it doesn't really randomize, but seems to present me with a static team based on my IP address. Refreshing didn't change the composition I was given, but using different IP addresses did. For example, I used "localhost", then "[my local IP address]", then finally "[my public IP address]" and got three different results. I'm not sure if this is intentional or if I did something wrong during the install.

**Comment by Herringway** [comment]
yeah, it's intentional. I wanted it to be easier to get the party back in case the browser tab was closed. You can add `?trand` to the end of the URL to force it to generate a new one every time, though.

**Comment by princessGasmask** [comment]
Got you. Thanks!
